# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great StackOverflow post.




### Using NumPy


In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays
NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays From a Python List



In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods


### arange
Return evenly spaced values within a given interval.



In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

### zeros and ones
Generate arrays of zeros or ones



In [9]:
np.zeros(3)


array([0., 0., 0.])

### Strings

In [10]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)


array([1., 1., 1.])

In [12]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.



In [13]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Creates an identity matrix



In [15]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
Numpy also has lots of ways to create random number arrays:

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).




In [16]:
np.random.rand(2)


array([0.72311414, 0.36331743])

In [17]:
np.random.rand(5,5)


array([[0.69454756, 0.55929888, 0.9150749 , 0.29593844, 0.70493658],
       [0.82574748, 0.40099971, 0.85786806, 0.05327901, 0.42130348],
       [0.29948894, 0.44744878, 0.74871138, 0.83397756, 0.97879302],
       [0.52571516, 0.58971227, 0.46998452, 0.88608186, 0.24829606],
       [0.07315472, 0.1636634 , 0.79534779, 0.30413146, 0.25965449]])

#### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:



In [18]:
np.random.randn(2)


array([-0.46316803,  0.36930297])

In [19]:
np.random.randn(5,5)


array([[ 0.3436645 ,  0.43341773,  1.59751282, -1.52958051,  0.23877125],
       [ 0.77299611,  1.44703889,  0.04509972,  0.43455639,  0.14080399],
       [-0.89483435,  0.19451677,  0.83137626, -0.75074961, -0.12838635],
       [-0.85596421,  0.17121109, -0.51500526,  0.36575894,  0.25385729],
       [ 2.0930548 , -0.78754211, -0.48150708, -0.24074625, -1.33450816]])

### randint
Return random integers from low (inclusive) to high (exclusive).




In [20]:
np.random.randint(1,100)


16

In [21]:
np.random.randint(1,100,10)


array([ 8,  8, 85, 16, 60, 19, 42, 89,  2,  6])

## Array Attributes and Methods
Let's discuss some useful attributes and methods or an array:




In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([40, 39, 25,  2, 48,  4, 29, 19, 21, 27])

### Reshape
Returns an array containing the same data with a new shape.



In [25]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax




In [26]:
ranarr

array([40, 39, 25,  2, 48,  4, 29, 19, 21, 27])

In [27]:
ranarr.max()


48

In [28]:
ranarr.argmax()


4

In [29]:
ranarr.min()


2

In [30]:
ranarr.argmin()


3

## Shape
Shape is an attribute that arrays have (not a method):



In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape


(1, 25)

In [34]:
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape


(25, 1)

### dtype
You can also grab the data type of the object in the array:

In [36]:
arr.dtype


dtype('int64')